#!/usr/bin/env bash
# Phase B — reasoning/QA arm, fully automated over MODELS_TO_RUN x BENCHMARKS_TO_RUN.
# Per (model,bench): prepare -> baseline train-gen (2 GPU) -> compress+build (2 GPU)
#   -> register -> LoRA SFT (2 GPU) -> peft merge -> measured sweep (1 GPU, GPU+PDU monitors) -> score.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

DATA_DIR="$REPO_ROOT"
LF_DATA="$REPO_ROOT/LlamaFactory/data"
DS_INFO="$LF_DATA/dataset_info.json"

# one-time data prep for boolq/piqa
for b in $BENCHMARKS_TO_RUN; do
  if [[ "$b" == "boolq" || "$b" == "piqa" ]]; then
    if [[ ! -s "$REPO_ROOT/$b/datasets/$b/test.jsonl" ]]; then
      log "prepare data: $b"
      run "cd '$REPO_ROOT/$b' && conda run -n $TS_ENV python prepare.py"
    fi
  fi
done

baseline_traingen() { # 2 GPUs (NOT energy-measured)
  local out="outputs/$MF/$BENCH/"
  local preds="$REPO_ROOT/$BENCH/${out}${MSIZE}/Original/train/samples/predictions.jsonl"
  if [[ -s "$preds" ]]; then log "baseline train-gen exists -> skip ($BENCH/$MF)"; return; fi
  log "baseline train-gen [2 GPU] $MF/$BENCH"
  run "cd '$REPO_ROOT/$BENCH' && CUDA_VISIBLE_DEVICES=0,1 conda run -n $TS_ENV python ../common/evaluation.py \
        --output-dir '$out' --model-path '$LOCAL_MODEL' --tokenizer-path '$LOCAL_MODEL' \
        --model-size '$MSIZE' --model-type '$MTYPE' --data-type train --compression_ratio 1.0 \
        --max_new_tokens $TRAINGEN_MAX_NEW_TOKENS --eval_batch_size $EVAL_BATCH_SIZE \
        --temperature $TEMPERATURE --seed $SEED --benchmark '$BENCH' --use_vllm"
}

compress_build() { # 2 GPUs ok (compressor is small; not measured)
  local sft="$REPO_ROOT/$BENCH/outputs/$MF/$BENCH/mydataset_${BENCH}_${MODEL_NAME}_${MSIZE}.json"
  if [[ -s "$sft" ]]; then log "SFT json exists -> skip compress/build ($BENCH/$MF)"; SFT_JSON="$sft"; return; fi
  log "compress + build SFT [GPU] $MF/$BENCH"
  run "CUDA_VISIBLE_DEVICES=0,1 conda run -n $TS_ENV python '$AUTO_DIR/_compress_build.py' \
        --bench '$BENCH' --model-folder '$MF' --size '$MSIZE' --mtype '$MTYPE' \
        --model-name '$MODEL_NAME' --builder '$MBUILDER' \
        --bench-dir '$REPO_ROOT/$BENCH' --llmlingua '$LLMLINGUA_CKPT'"
  SFT_JSON="$sft"
}

register_dataset() {
  DS_KEY="tokenskip_${MODEL_NAME}_${MSIZE}_${BENCH}"
  local dst="$LF_DATA/${DS_KEY}.json"
  run "mkdir -p '$LF_DATA' && cp -f '$SFT_JSON' '$dst'"
  run "conda run -n $TS_ENV python '$AUTO_DIR/_register_dataset.py' '$DS_INFO' '$DS_KEY' '${DS_KEY}.json'"
}

gen_yaml() {
  ADAPTER_DIR="$REPO_ROOT/LlamaFactory/lora_saves/$MF/lora/${BENCH}_test"
  YAML="$REPO_ROOT/common/configs/auto_${MODEL_NAME}_${MSIZE}_${BENCH}.yaml"
  if [[ "${DRY_RUN:-0}" == "1" ]]; then echo "  + write $YAML"; return; fi
  cat > "$YAML" <<EOF
### auto-generated by auto/10_reasoning.sh
model_name_or_path: $LOCAL_MODEL
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
dataset: $DS_KEY
dataset_dir: $LF_DATA
template: $MTEMPLATE
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: $ADAPTER_DIR
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
optim: adamw_torch
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 300
EOF
  echo "  + wrote $YAML"
}

lora_train() { # 2 GPUs (required)
  if [[ -f "$ADAPTER_DIR/adapter_model.safetensors" || -f "$ADAPTER_DIR/adapter_model.bin" ]]; then
    log "adapter exists -> skip SFT ($BENCH/$MF)"; return; fi
  log "LoRA SFT [2 GPU] $MF/$BENCH"
  run "cd '$REPO_ROOT' && CUDA_VISIBLE_DEVICES=0,1 conda run -n $LF_ENV llamafactory-cli train '$YAML'"
}

merge_adapter() { # peft, tokenskip_env
  MERGED="$DATA_ROOT/merged/${MF}-${BENCH}"
  if [[ -f "$MERGED/config.json" ]]; then log "merged model exists -> skip ($BENCH/$MF)"; return; fi
  log "merge adapter -> $MERGED"
  run "conda run -n $TS_ENV python '$REPO_ROOT/common/merge.py' --base '$LOCAL_MODEL' --adapter '$ADAPTER_DIR' --output '$MERGED'"
}

measured_sweep() { # 1 GPU ONLY + GPU/PDU monitors
  log "measured sweep [1 GPU] $MF/$BENCH  (tokens={$SWEEP_TOKENS} ratios={$SWEEP_RATIOS} x$SWEEP_REPEATS)"
  local T r k base rid
  for T in $SWEEP_TOKENS; do
    for r in $SWEEP_RATIOS; do
      for k in $(seq 1 "$SWEEP_REPEATS"); do
        base="$REPO_ROOT/$BENCH/outputs_sweep/$MF/$BENCH/tok${T}/run${k}"
        rid="${MSIZE}_${BENCH}_tok${T}_ratio${r}_run${k}"
        run "mkdir -p '$base'"
        if [[ "${DRY_RUN:-0}" == "1" ]]; then
          echo "  + [eval] CUDA_VISIBLE_DEVICES=0 evaluation.py merged ratio=$r tok=$T -> $base"; continue; fi
        # start monitors (GPU 0 + optional PDU)
        python3 "$REPO_ROOT/common/monitor_gpu.py" --run-name "$rid" --output-dir "$base" --interval "$MONITOR_INTERVAL" & GPU_PID=$!
        PDU_PID=""
        [[ "${ENABLE_PDU:-1}" == "1" ]] && { python3 "$REPO_ROOT/common/monitor_pdu.py" --run-name "$rid" --output-dir "$base" --interval "$MONITOR_INTERVAL" & PDU_PID=$!; }
        # gamma=1.0 = uncompressed baseline -> pristine BASE model (the merged/SFT model
        # collapses to ~0 CoT without a gamma marker). gamma<1.0 -> merged compression model.
        EVAL_MODEL="$MERGED"
        [[ "$r" == "1.0" ]] && EVAL_MODEL="$LOCAL_MODEL"
        # SINGLE-GPU measured inference; ratio marker injected by --compression_ratio.
        # run from the benchmark folder so evaluation.py finds configs/ and datasets/ (relative paths)
        ( cd "$REPO_ROOT/$BENCH" && CUDA_VISIBLE_DEVICES=0 conda run -n "$TS_ENV" python "$REPO_ROOT/common/evaluation.py" \
            --output-dir "$base" --model-path "$EVAL_MODEL" --tokenizer-path "$EVAL_MODEL" \
            --model-size "$MSIZE" --model-type "$MTYPE" --data-type test \
            --max_new_tokens "$T" --eval_batch_size "$EVAL_BATCH_SIZE" \
            --temperature "$TEMPERATURE" --seed "$SEED" --benchmark "$BENCH" \
            --use_vllm --compression_ratio "$r" )
        kill -2 "$GPU_PID" 2>/dev/null || true
        [[ -n "$PDU_PID" ]] && { kill -2 "$PDU_PID" 2>/dev/null || true; }
        sleep 10
      done
    done
  done
}

for key in $MODELS_TO_RUN; do
  model_spec "$key" || continue
  if [[ ! -f "$LOCAL_MODEL/config.json" && "${DRY_RUN:-0}" != "1" ]]; then
    warn "$key: base model not at $LOCAL_MODEL — run 00_setup.sh first"; continue; fi
  for BENCH in $BENCHMARKS_TO_RUN; do
    log "================  $key / $BENCH  ================"
    baseline_traingen
    compress_build
    register_dataset
    gen_yaml
    lora_train
    merge_adapter
    measured_sweep
  done
done

log "Reasoning arm complete. Scores in each run's samples/metrics.json; energy in *_gpu.json / *_pdu.json."
